version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  test: 
    jobs:
      - test:
          context:
            - context-test

jobs:
  test: 
    docker:
      - image: cimg/python:3.8
    steps:
       - run: echo $TEST this should be run twice!
